### ISSUE TITLE
Installation error Blender 2.93

### ISSUE THREAD

**Issue by Sinasta** [vicdoval/sverchok-open3d#1]
Thanks for your work. I get this error on activation on blender 2.93:

2021-03-12 16:51:20,436  WARNING warnings.py 109 /home/sinasta/.config/blender/2.93/scripts/addons/sverchok-open3d-master/settings.py:5: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python

Traceback (most recent call last):
  File "/usr/share/blender/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/sinasta/.config/blender/2.93/scripts/addons/sverchok-open3d-master/__init__.py", line 36, in <module>
    from sverchok_open3d import icons, settings, sockets, examples, menu
  File "/usr/lib/python3.9/site-packages/shiboken2/files.dir/shibokensupport/__feature__.py", line 142, in _import
    return original_import(name, *args, **kwargs)
  File "/home/sinasta/.config/blender/2.93/scripts/addons/sverchok-open3d-master/settings.py", line 9, in <module>
    from sverchok.utils.context_managers import addon_preferences
ImportError: cannot import name 'addon_preferences' from 'sverchok.utils.context_managers' (/home/sinasta/.config/blender/2.93/scripts/addons/sverchok-master/utils/context_managers.py)

**Comment by vicdoval** [comment]
Hi @Sinasta and thank you for testing and reporting, right know the addon only works with this branch  of Sverchok https://github.com/vicdoval/sverchok/tree/extra_addons_support. 
This will change very soon (probably tomorow)
Sorry for the inconveniece but i wanted to leave some time with the [Pull Request](https://github.com/nortikin/sverchok/pull/3966)  open in the Sverchok repo before merging all the new changes. I will keep you informed

**Comment by Sinasta** [comment]
thank you very much for your answer! I am looking forward to test your addon!

**Comment by vicdoval** [comment]
It should be working now with last Sverchok commits

**Comment by maxim1967** [comment]
Hello. Unfortunately, your Addon will not work with Blender 2.93 yet, since the main library runs on Python 3.8 and Blender 2.93 on Python 3.9

**Comment by vicdoval** [comment]
Thanks for reporting it. It seems a dependency chain problem. Seems it will be fixed by the end of April probably earlier than the official  2.93 release https://github.com/intel-isl/Open3D/issues/3065

**Comment by nortikin** [comment]
```
    import ipywidgets as widgets
ModuleNotFoundError: No module named 'ipywidgets'
```
but ipywidgets installed... hm dependencies

**Comment by nortikin** [comment]
now pycups have not been installed due to absence of Python header c++ file
cannot install conda locally for same reason, Python.h
```bash
Installing collected packages: pycups
    Running setup.py install for pycups ... error
    ERROR: Command errored out with exit status 1:
     command: /home/ololo/Downloads/INSTALL/blender-2.92.0-linux64/2.92/python/bin/python3.7m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f3cqky6c/pycups_1f4460d927884c42b307903381c0a93a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f3cqky6c/pycups_1f4460d927884c42b307903381c0a93a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9qy0hefq/install-record.txt --single-version-externally-managed --compile --install-headers /home/ololo/Downloads/INSTALL/blender-2.92.0-linux64/2.92/python/include/python3.7m/pycups
         cwd: /tmp/pip-install-f3cqky6c/pycups_1f4460d927884c42b307903381c0a93a/
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'cups' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/blender/Developer/build_linux/deps/Release/sqlite/include -I/home/blender/Developer/build_linux/deps/Release/bzip2/include -I/home/blender/Developer/build_linux/deps/Release/lzma/include -I/home/blender/Developer/build_linux/deps/Release/zlib/include -fPIC -fPIC -DVERSION="2.0.1" -I/home/ololo/Downloads/INSTALL/blender-2.92.0-linux64/2.92/python/include/python3.7m -c cupsmodule.c -o build/temp.linux-x86_64-3.7/cupsmodule.o
    cupsmodule.c:23:10: fatal error: Python.h: Нет такого файла или каталога
     #include <Python.h>
              ^~~~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/ololo/Downloads/INSTALL/blender-2.92.0-linux64/2.92/python/bin/python3.7m -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f3cqky6c/pycups_1f4460d927884c42b307903381c0a93a/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f3cqky6c/pycups_1f4460d927884c42b307903381c0a93a/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-9qy0hefq/install-record.txt --single-version-externally-managed --compile --install-headers /home/ololo/Downloads/INSTALL/blender-2.92.0-linux64/2.92/python/include/python3.7m/pycups Check the logs for full command output.

```

**Comment by nortikin** [comment]
link to site is to freecad, not oppen3d

**Comment by JuanJ67m** [comment]
2.92 also with problems
@vicdoval  @ranska  @portnov 

```

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\JTM_PC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-open3d-master\__init__.py", line 64, in <module>
    imported_modules = [icons] + make_node_list()
  File "C:\Users\JTM_PC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-open3d-master\__init__.py", line 51, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "C:\Program Files\Blender Foundation\Blender 2.92\2.92\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\JTM_PC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-open3d-master\nodes\point_cloud\point_cloud_in.py", line 10, in <module>
    from sverchok.data_structure import updateNode, has_element
ImportError: cannot import name 'has_element' from 'sverchok.data_structure' (C:\Users\JTM_PC\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\sverchok-vstable8\data_structure.py)


```

**Comment by vicdoval** [comment]
@JuanJ67m  Please update your Sverchok

**Comment by nortikin** [comment]
it not installing not in windows nor in linux.
pressing pip doing installation, but when i want to get nodes - there are no nodes, only proposal for install open3d.
```bash
   _____                     __          __         ______     __
  / ___/   _____  __________/ /_  ____  / /__      / ____/  __/ /__________ _
  \__ \ | / / _ \/ ___/ ___/ __ \/ __ \/ //_/_____/ __/ | |/_/ __/ ___/ __ `/
 ___/ / |/ /  __/ /  / /__/ / / / /_/ / ,< /_____/ /____>  </ /_/ /  / /_/ /
/____/|___/\___/_/   \___/_/ /_/\____/_/|_|     /_____/_/|_|\__/_/   \__,_/
initialized.
2021-05-18 14:30:20,085 [INFO] ladybug: Successfully imported Ladybug plugin: ladybug_tools
2021-05-18 14:30:20,106 [INFO] ladybug: Successfully imported Ladybug plugin: ladybug_comfort
2021-05-18 14:30:20,117 [INFO] ladybug: Successfully imported Ladybug plugin: ladybug_geometry
2021-05-18 14:30:21,028 [INFO] ladybug_tools: Registered 67 nodes
2021-05-18 14:30:21,067 [WARNING] py.warnings: C:\Users\%username%\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\sverchok-open3d-master\settings.py:5: RuntimeWarning: Use 'sys.executable' instead of 'binary_path_python'!
  PYPATH = bpy.app.binary_path_python

2021-05-18 14:30:21,233 [INFO] sverchok_open3d.dependencies: open3d package is not available, the addon will not work
2021-05-18 14:30:21,568 [INFO] sverchok-open3d-master: Registered 25 nodes
2021-05-18 14:30:21,603 [INFO] sverchok-open3d-master: Node `SvO3ImportNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,634 [INFO] sverchok-open3d-master: Node `SvO3ExportNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,664 [INFO] sverchok-open3d-master: Node `SvO3Transform' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,694 [INFO] sverchok-open3d-master: Node `SvO3PointCloudInNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,727 [INFO] sverchok-open3d-master: Node `SvO3PointCloudOutNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,768 [INFO] sverchok-open3d-master: Node `SvO3PointCloudDownSampleNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,802 [INFO] sverchok-open3d-master: Node `SvO3PointCloudMaskNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,835 [INFO] sverchok-open3d-master: Node `SvO3PointCloudJoinNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,875 [INFO] sverchok-open3d-master: Node `SvO3PointCloudCalcNormalsNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,913 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshInNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,946 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshOutNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:21,982 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshFromPointCloudNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,015 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSamplingNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,048 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSimplifyNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,081 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSubdivideNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,112 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshPokeNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,145 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSmoothNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,180 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSharpenNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,215 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshDeformAsRigidNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,253 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshMaskNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,289 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSeparateNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,319 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshJoinNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,349 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshIntersectNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,379 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSelfIntersectNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,410 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshCleanNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,441 [INFO] sverchok-open3d-master: Node `SvO3ImportNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,474 [INFO] sverchok-open3d-master: Node `SvO3ExportNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,506 [INFO] sverchok-open3d-master: Node `SvO3Transform' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,537 [INFO] sverchok-open3d-master: Node `SvO3PointCloudInNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,568 [INFO] sverchok-open3d-master: Node `SvO3PointCloudOutNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,600 [INFO] sverchok-open3d-master: Node `SvO3PointCloudDownSampleNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,630 [INFO] sverchok-open3d-master: Node `SvO3PointCloudMaskNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,660 [INFO] sverchok-open3d-master: Node `SvO3PointCloudJoinNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,691 [INFO] sverchok-open3d-master: Node `SvO3PointCloudCalcNormalsNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,723 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshInNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,756 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshOutNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,786 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshFromPointCloudNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,817 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSamplingNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,847 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSimplifyNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,884 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSubdivideNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,915 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshPokeNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,945 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSmoothNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:22,975 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSharpenNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:23,006 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshDeformAsRigidNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:23,037 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshMaskNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:23,069 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSeparateNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:23,099 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshJoinNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:23,129 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshIntersectNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:23,158 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshSelfIntersectNode' is not available (probably due to missing dependencies).
2021-05-18 14:30:23,190 [INFO] sverchok-open3d-master: Node `SvO3TriangleMeshCleanNode' is not available (probably due to missing dependencies).

   +----------------------------+
   |                            |
   |     SVERCHOK - OPEN3D      |
   |                            |
   +----------------------------+
   initialized.
```

**Comment by vicdoval** [comment]
@nortikin What version of blender are you using?

**Comment by nortikin** [comment]
> @nortikin What version of blender are you using?

windows is 2.91, linux is 2.92 and 3.0.0
